--- #YAML:1.0
name:                B-Debug
version:             1.08
abstract:            print debug info about ops
license:             perl
author:            
    - Malcolm Beattie <mbeattie@sable.ox.ac.uk>, Reini Urban <rurban@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:
    B: 0
recommends:
    B::Flags:    0.02
provides:
    B::Debug     
meta-spec:
    version: 1.3
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
